// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzsvhbewcsvzqvzffpfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6c3ZoYmV3Y3N2enF2emZmcGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzcxNTYsImV4cCI6MjA2NTU1MzE1Nn0.r6URI_L76kZk8aEFf8H7F5WwrROJaQddZHbE-2dAcZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);